### ISSUE TITLE
Одновременно не запускаются

### ISSUE THREAD

**Issue by tarakan1983** [2UTM/2UTM#1]
Здравствуйте.
После нажатия на кнопку "Запустить УТМы" идет долгий запуск и потом вылет в Execption.
![Screenshot_1](https://user-images.githubusercontent.com/43087425/163025506-db94daf0-7b99-415e-b68f-956fe60dbb92.png)
[Exception.txt](https://github.com/2UTM/2UTM/files/8475420/Exception.txt)
В итоге UTM_2 запущен, UTM - нет. Пробовал запускать службу руками, не стартует.
[log.txt](https://github.com/2UTM/2UTM/files/8475432/log.txt)
[transport_info.log](https://github.com/2UTM/2UTM/files/8475433/transport_info.log)

**Comment by 2UTM** [comment]
какая ос?

**Comment by tarakan1983** [comment]
Win 7 x64

**Comment by 2UTM** [comment]
по логам проблема с получением дочерних элементов, есть проблема такая, распространена на версиях home...
на pro должно работать...
а appcrash потому что уходит за предел вектора, это конечно ошибка, такого быть не должно...
идет работа над обновлением, там будут изменены все алгоритмы, больше будет упор на API от рутокенов, и таких ошибок не будет

**Comment by tarakan1983** [comment]
Версия Win7 x64 Ultimate. С нетерпением жду обновление.
Подскажите, возможность установки только 2-х УТМ? Если исходить из логики работы приложения, то может можно добавить n-количество УТМ ?

**Comment by 2UTM** [comment]
можно будет добавить до 8 утм (больше никто пока не просил), но алгоритм будет так построен, что можно будет добавить столько утм, на сколько хватит памяти

**Comment by 2UTM** [comment]
можете попробовать новую версию

**Comment by tarakan1983** [comment]
После перезагрузки и команды "запустить УТМыЭ
![Screenshot_1](https://user-images.githubusercontent.com/43087425/172657319-0c35c32a-884d-432d-b9a8-58dfe8c90906.png)
[Exception.txt](https://github.com/2UTM/2UTM/files/8863077/Exception.txt)

**Comment by 2UTM** [comment]
log покажите

upd
вообще больше похоже на какой то конфликт qt, ошибка в библиотеке qt5core
многие люди пользуются, таких ошибок нет
и у себя таких ошибок не замечал на разных ОС (в win7 ultimate не тестил)

расскажите подробнее, после чего появляется ошибка:
без перезагрузки все работает? 
после перезагрузки рутокены видны?
после перезагрузки ридеры не сменили имена?
