### ISSUE TITLE
Перезапуск программы

### ISSUE THREAD

**Issue by Stelz481** [2UTM/2UTM#10]
Добрй день. Пользуюсь версией программы 1.2.1 , подскажите пожалуйста возможен ли перезапуск утм? 
Столкнулся с проблемой что в течение дня утм не доступны. Лечу перезапуском прорагммы и запуском УТМ.

**Comment by 2UTM** [comment]
в меню программы есть остановка утм и запуск утм, получается перезапуск

**Comment by Stelz481** [comment]
а автоматически можно поставить проверку на запущенный утм?

**Comment by 2UTM** [comment]
такого функционала в программе нет, так как задумывалось, что программа не контролирует работу утм
если нужно, добавлю в след версии

**Comment by 2UTM** [comment]
предыдущий комент как бы подразумевал, что вы ответите, насколько это необходимо...

**Comment by unnamed63** [comment]
Добрый день! Отличная программа, установил два УТМ, но выяснилось, что после перезагрузки ПК оба УТМ остановлены, приходится запускать программу, и в ней запускать УТМы, хотелось бы автозапуск!)

**Comment by 2UTM** [comment]
будет в обновлении недели через две, тестирую

**Comment by 2UTM** [comment]
попробуйте новую версию

**Comment by unnamed63** [comment]
Сорри, был в отпуске, сразу не обновил) Сейчас проверил, обновился, установил службу, обновил винду и перезапустил комп, один УТМ запустился сразу же, второй буквально через пару минут! Всё отлично, спасибо огромное!
