### ISSUE TITLE
Возможность устанавливать одну УТМ

### ISSUE THREAD

**Issue by Oxotnik26** [2UTM/2UTM#2]
Спасибо за программу. Не знаю что ты сделал, но мои 5 УТМ работают уже больше 48 часов и ещё не разу не вылетели.
Может стоит разрешить устанавливать одну УТМ с помощью твоей программы? Что бы не мучаться с множественными остановками УТМ.

**Comment by 2UTM** [comment]
программа не контролирует работу УТМов, она просто устанавливает, удаляет, запускает и останавливает их.
УТМ и сам довольно стабилен, кроме вебморды, но в последних версиях вроде починили.
не понял, что значит "не мучаться с множественными остановками УТМ".
один утм и так можно установить в один клик...

**Comment by Oxotnik26** [comment]
У меня на 3-х компьютерах(windows) и у знакомого на ноутбуке(windows) проблема с УТМ, уже где-то пол года. УТМ зависала, переставал работать веб интерфейс и приём/передача документов. Помогал только перезапуск УТМ и такое могло происходить 5 раз в день. Но иногда не помогал и перезапуск. Приходилось вытаскивать рутокен и вставлять его обратно, только тогда УТМ запускался.
Появилась необходимость в большем количестве УТМ и я перенёс все мои УТМ на один компьютер, с помощью виртуальной машины VirtualBox. В качестве ОС использовал чистый Debian, но и это не решило проблем. УТМ всё также зависали.
Но когда я установил 5 УТМ с помощью твоей программы, они перестали вылетать. С 1.08 по 5.08 не было ни одного зависания.

**Comment by 2UTM** [comment]
чудеса прям какие то))
но могу заверить - это не связанно с моей программой, она не контролирует работу УТМов

**Comment by Oxotnik26** [comment]
Возможно это связано с точным указанием для УТМ с каким ключом ей работать?

**Comment by 2UTM** [comment]
нет, УТМ берет первый токен, который есть в системе

**Comment by Oxotnik26** [comment]
То есть 2UTM берёт все токены поочереди?
Чуть попозже создам новую ветку с багом(2UTM повреждает реестр).

**Comment by 2UTM** [comment]
программа удаляет ридеры, и добавляет их с конца, то есть запуск утм идет с последнего утма
