### ISSUE TITLE
Не запускаются УТМ и пропадают ключи Рутокен. Повреждение реестра.

### ISSUE THREAD

**Issue by Oxotnik26** [2UTM/2UTM#3]
Пример: Есть 3 ключа, из них ECP 0(Михаил) и ECP 2(Валера) поменялись местами и стали ECP 0(Валера) и ECP 2(Михаил), ECP1(Ольга) остался на том же месте. Если такое произошло, то 2UTM не сможет запустить УТМ 0, УТМ 2 и закроется без объявления ошибки. При этом рутокены 0 и 2 пропадут из панели управления рутокенами. Смена рутокенов у меня произошла из-за перезагрузки ПК, 2 раза.

Почему не запустились УТМы легко понять. Если в ECP 0 стоит другой сертификат (Валера), то УТМ 0 (Михаил) настроенный на другого пользователя просто не стартанёт.

**Почему пропали рутокены из панели и как это исправить**
Если мы после пропажи рутокенов вытащим их из ПК и вставим назад или перезагрузим компьютер, то мы получим такую картину. 
![2022-08-10_12-56-41](https://user-images.githubusercontent.com/21249519/183885313-f191988d-9f55-4055-82e9-df6d9ce905dc.png)
Есть ECP 1 и 2, но нет ECP 0. Исправить это можно только через редактирование реестра.
Нам нужна эта ветка реестра: Компьютер\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\Readers ![2022-08-10_13-05-19](https://user-images.githubusercontent.com/21249519/183885444-84755b6b-8dbb-4f64-867c-3aed0201d0a4.png)
В ней будет отсутствовать раздел Aktiv Rutoken ECP 0 и если ничего не делать с ключами рутокен(сразу после 2UTM), то и раздел Aktiv Rutoken ECP 2. Нам надо создать раздел Aktiv Rutoken ECP 0 и заполнить его по примеру другого рутокена или удалить все разделы и вытащить/вставить все ключи. После совершения данных манипуляций ECP 0 появится в панели управления.

Чтобы восстановить последовательность рутокенов надо:
- знать какому УТМ какой сертификат соответствует ![2022-08-10_13-35-14](https://user-images.githubusercontent.com/21249519/183885584-bcbcbe82-9112-423c-9aac-3620ff4d6a9d.png)
- через панель управления рутокен посмотреть какому ECP какой сертификат соответствует
- в реестре Компьютер\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Calais\Readers поменять наименования разделов в нужной последовательности (!!только наименования разделов!!) (Aktiv Rutoken ECP 2 в Aktiv Rutoken ECP 0 и Aktiv Rutoken ECP 0 в Aktiv Rutoken ECP2, из примера). Должно получится так ![2022-08-10_13-29-14](https://user-images.githubusercontent.com/21249519/183885633-2d040df8-c718-491e-b691-7bb48d31ce0d.png)

После завершения данных действий можно запускать УТМы.

**Comment by 2UTM** [comment]
Покажите лог, и создался ли в папке с программой файл config.ini?

**Почему пропали рутокены из панели и как это исправить**
Они не пропали, просто ридеры удалились, возникла не предвиденная ошибка и операция прервалась, в штатном режиме рутокены никуда не пропадают

**Исправить это можно только через редактирование реестра.**
Нет, можно отключить все токены и подключить их заново, физически или через диспетчер устройств
Так же можно удалить все ридеры вне контекста через программу (вне контекста, то есть ридеры есть, а физических устройств нет)

Ошибка похожа на то, что config.ini не создался, и поэтому программа просто не знала что делать, по какой причине не создается config.ini, я пока не выяснил, возможно ошибка в qt, в тестах я такого не наблюдал, но вы уже третий с похожей ошибкой

Жду от вас лог и инфу по файлу config.ini

**Comment by Oxotnik26** [comment]
[Логи, настройки и запись экрана с помощью AnyDesk](https://disk.yandex.ru/d/6j5ZbzDPcLoP0Q)
Конфиг создался и лог почти пустой, нет сообщений об ошибке.
Понятно что в штатном режиме они не пропадают. Но если ридеры содержат другие сертификаты, то 2UTM удаляет эти ридеры из реестра. Перезарузка или передёргивание ключей помогает частично. Я очень долго пытался восстановить ридер 0 и 3. Менял USB порты, последовательность подключений ключей в эти порты, удалял драйвера рутокенов, в диспетчере задач тоже удалял. Только реестр помог.
Удаление всех ридеров в разделе "ридеры вне контекста", удаляет их из реестра. Получается тоже самое. Всё равно после этого надо лезть в реестр и ставить нужные цифры в ручном режиме. 

Посмотри видео. Я перезагрузил ПК и запустил 2UTM. Лог выложил после видео.
Можно в выходные подключиться к моему ПК и повторить действия приводящие к проблеме. Надо будет только согласовать способ связи, а время любое после 11:00.

**Comment by 2UTM** [comment]
**Удаление всех ридеров в разделе "ридеры вне контекста", удаляет их из реестра. Получается тоже самое. Всё равно после этого надо лезть в реестр и ставить нужные цифры в ручном режиме.**
Не обязательно лезть в реестр, можно в конфиге поменять имя считывателя и атрибут считывателя, они видны в программе

И смарт карты в диспетчере устройств нужно не удалять, а отключать все и затем включать все
При удалении устройства обновляются, и он опять находит эти смарт карты, и сажает их уже на существующие ридеры
Чтобы вернуть ридеры, достаточно просто отключить все смарт карты, затем их подключить
Или сначала удалить все ридеры через программу, а затем просто отключить все смарт карты, затем их подключить

Посмотрите лог системы, какая там ошибка

В конфиге есть параметры токенов, в программе, если их выбрать в списке, эти параметры так же видны, посмотрите в чем отличие после перезагрузки, это поможет мне воспроизвести ошибку у себя





,

**Comment by Oxotnik26** [comment]
Изменение конфига помогает.

Отключение смарт карт попробую вечером.

В логе нет ошибок, программа закрывается без ошибки. Ошибки появлялись только когда я копался в конфиге или пытался запустить 4 из 5-ти УТМов.

После перезагрузки некоторые токены меняются местами. К примеру токен который до перезагрузки был по номером 0, после перезагрузки его можно найти под номером 3. А на месте нулевого будет тройка или другой номер. И соответственно на токене 0 меняются серийный номер и сертификаты. По идее если в конфиге поменять серийные номера местами то можно получить мою ситуацию или номера считывателей. Вечером проверю.

**Comment by 2UTM** [comment]
**В логе нет ошибок, программа закрывается без ошибки**
Если она закрывается неожиданно, значит это ошибка, вы наверное не поняли про лог, я говорю о системном логе, он находиться панель управления -> администрирование -> просмотр событий

**Comment by Oxotnik26** [comment]
Ошибка	11.08.2022 11:45:24	Application Error	1000	(100)
Имя сбойного приложения: 2UTM_new.exe, версия: 0.0.0.0, метка времени: 0x628d1566
Имя сбойного модуля: msvcrt.dll, версия: 7.0.19041.546, метка времени: 0x7f567a50
Код исключения: 0xc0000005
Смещение ошибки: 0x0008915a
Идентификатор сбойного процесса: 0x25fc
Время запуска сбойного приложения: 0x01d8ad5e111c99a9
Путь сбойного приложения: C:\Program Files (x86)\2UTM\2UTM_new.exe
Путь сбойного модуля: C:\WINDOWS\System32\msvcrt.dll
Идентификатор отчета: c18eb410-a55e-4ffb-9e69-a994cb246f04
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 

Пояснение к первой ошибке: После изменения в конфиге. Не запустился 1 УТМ и программа вылетела. Добавил вылетевший токен в реестр и всё заработало. Экспериментировать буду вечером.


Ошибка	11.08.2022 1:26:51	Application Error	1000	(100)
Имя сбойного приложения: 2UTM_new.exe, версия: 0.0.0.0, метка времени: 0x628d1566
Имя сбойного модуля: Qt5Core.dll, версия: 5.12.6.0, метка времени: 0x5dc715c9
Код исключения: 0xc0000005
Смещение ошибки: 0x00179456
Идентификатор сбойного процесса: 0x1a50
Время запуска сбойного приложения: 0x01d8ad084735eca4
Путь сбойного приложения: C:\Program Files (x86)\2UTM\2UTM_new.exe
Путь сбойного модуля: C:\Program Files (x86)\2UTM\Qt5Core.dll
Идентификатор отчета: d4e4f7c3-ce80-48a4-b80b-b2fc10992c99
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 

Ошибка	11.08.2022 1:08:53	Application Error	1000	(100)
Имя сбойного приложения: 2UTM_new.exe, версия: 0.0.0.0, метка времени: 0x628d1566
Имя сбойного модуля: msvcrt.dll, версия: 7.0.19041.546, метка времени: 0x7f567a50
Код исключения: 0xc0000005
Смещение ошибки: 0x0008915a
Идентификатор сбойного процесса: 0x2488
Время запуска сбойного приложения: 0x01d8ad053cf1e80f
Путь сбойного приложения: C:\Program Files (x86)\2UTM\2UTM_new.exe
Путь сбойного модуля: C:\WINDOWS\System32\msvcrt.dll
Идентификатор отчета: 2b8688ce-0a02-4e25-99bd-8feb9a441bf3
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 

Ошибка	11.08.2022 0:41:22	Application Error	1000	(100)
Имя сбойного приложения: 2UTM_new.exe, версия: 0.0.0.0, метка времени: 0x628d1566
Имя сбойного модуля: msvcrt.dll, версия: 7.0.19041.546, метка времени: 0x7f567a50
Код исключения: 0xc0000005
Смещение ошибки: 0x0008915a
Идентификатор сбойного процесса: 0xee8
Время запуска сбойного приложения: 0x01d8ad01c81d98b7
Путь сбойного приложения: C:\Program Files (x86)\2UTM\2UTM_new.exe
Путь сбойного модуля: C:\WINDOWS\System32\msvcrt.dll
Идентификатор отчета: cea68c6a-f358-4720-90fe-d2fd6d989d00
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:

**Comment by 2UTM** [comment]
Попробую воспроизвести вашу ошибку

**Comment by Oxotnik26** [comment]
Итак. Ээээксперимент.
1. Перезагрузил компьютер. Удалил все ридеры из реестра и отключил/включил "Устройства чтения смарт карт" в диспетчере задач. Ридеры вновь появились в реестре.
2. Запустил УТМы через 2UTM:

а. Запустились 3 из 5. Очистил ридеры. Выключил/включил их в диспетчере задач. Все вернулись назад. УТМы отключил.

Ошибка	12.08.2022 0:37:37	Application Error	1000	(100)
Имя сбойного приложения: 2UTM_new.exe, версия: 0.0.0.0, метка времени: 0x628d1566
Имя сбойного модуля: msvcrt.dll, версия: 7.0.19041.546, метка времени: 0x7f567a50
Код исключения: 0xc0000005
Смещение ошибки: 0x0008915a
Идентификатор сбойного процесса: 0x365c
Время запуска сбойного приложения: 0x01d8adc9d43d2267
Путь сбойного приложения: C:\Program Files (x86)\2UTM\2UTM_new.exe
Путь сбойного модуля: C:\WINDOWS\System32\msvcrt.dll
Идентификатор отчета: cceae12a-9f5b-4f21-9134-99affff16604
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 

б. Запустились 4 из 5. Отсутствует ридер 0.  Ридеры не очищал. Выключил/включил их в диспетчере задач. Ридер 0 вернулся. УТМы отключил.

Ошибка	12.08.2022 0:47:44	Application Error	1000	(100)
Имя сбойного приложения: 2UTM_new.exe, версия: 0.0.0.0, метка времени: 0x628d1566
Имя сбойного модуля: msvcrt.dll, версия: 7.0.19041.546, метка времени: 0x7f567a50
Код исключения: 0xc0000005
Смещение ошибки: 0x0008915a
Идентификатор сбойного процесса: 0xc3c
Время запуска сбойного приложения: 0x01d8adcb55f76290
Путь сбойного приложения: C:\Program Files (x86)\2UTM\2UTM_new.exe
Путь сбойного модуля: C:\WINDOWS\System32\msvcrt.dll
Идентификатор отчета: 10ed710a-8621-40c9-b4b1-0cf1cc4a640c
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 

Обратил внимание, что когда 2UTM запускает УТМы программа удаляет все ридеры и создаёт их заново от 4 к 0. Наименование раздела(Aktiv Rutoken ECP 4) не всегда соответствует наименованию девайса (Device - Aktiv Rutoken ECP 2).

в. Очистил ридеры. Выключил/включил их в диспетчере задач. Все наименования разделов соответствуют значениям Device в реестре. Вернул конфиг 2UTM к первоначальному состоянию (до этого был изменён для соответствия сертификатов и УТМов).
Запустились 4 из 5 УТМов. Опять ошибка на ридере 0. Некоторые наименования разделов не соответствует наименованию девайса.

Ошибка	12.08.2022 1:09:24	Application Error	1000	(100)
Имя сбойного приложения: 2UTM_new.exe, версия: 0.0.0.0, метка времени: 0x628d1566
Имя сбойного модуля: msvcrt.dll, версия: 7.0.19041.546, метка времени: 0x7f567a50
Код исключения: 0xc0000005
Смещение ошибки: 0x0008915a
Идентификатор сбойного процесса: 0x16cc
Время запуска сбойного приложения: 0x01d8adced711a08d
Путь сбойного приложения: C:\Program Files (x86)\2UTM\2UTM_new.exe
Путь сбойного модуля: C:\WINDOWS\System32\msvcrt.dll
Идентификатор отчета: 0040c143-433e-4658-a5a0-eb88f28863f7
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 

г. Ридеры не очищал, только отключил/включил в диспетчере задач. УТМы не отключал. Запустил ещё раз 2 UTM нажал "Запустить УТМы". Программа запустила всё без проблем.

д. Перезагрузил компьютер. С ридерами ничего не делал, сразу запустил 2UTM. На удивление УТМы запустились без проблем.

е. Перезагрузил компьютер. В вариантах а - в убивал процесс автоматически стартовавшего УТМ. В варианте д я его не трогал. В этом варианте я его опять убил, потом запустил 2UTM и программа стартовала УТМы без проблем.

ё. Остановил УТМы, ридеры не трогал. В конфиге поменял серийные номера местами, между 0 и 2. Под ридером 3 изменил серийный номер на одну цифру. Программа ругнулась: Warning: Рутокены не совпадают с конфигом, запуск прерван. Серийный номер ридера 3 вернул к первоначальному значению, а серийники ридеров 0 и 2 оставил в поменянном состоянии. Программа нормально стартовала УТМы 5 и 4 (ECP 4 и 3). Попробовала стартовать УТМ 3 (ECP 2), процесс запустился но через пару секунд умер. Некоторое время повисев программа выдала ошибку: Warning: "Не удалось запустить службу Transport_3, функция не ответила и завершилась по таймауту". Но запустила УТМ 1, хотя ридеры 1 и 0 (разделы реестра) она не создала и УТМы 2 и 3 не запустила. В реестре видно что ридер 2 (раздел ECP 2) содержит значение Device - ECP 0.

з. Вернул конфиг в первоначальное состояние. Запустил УТМы по вариантам в. и г.. Как и в варианте в. программа сначала вылетела, а после повторения варианта г. запустила УТМы без ошибок.

Эксперимент окончен.

**Comment by 2UTM** [comment]
Ошибка в логике
По сути, в программе заложен функционал на случай перепутывания токенов, и в моих тестах все работало
Спасибо за содействие, вы очень помогли
Будет исправлено в след версиях

**Comment by 2UTM** [comment]
попробуйте новую версию
