### ISSUE TITLE
Скрипт на перезапуск всех УТМ

### ISSUE THREAD

**Issue by Hxcktivist** [2UTM/2UTM#4]
Доброго дня. Очень сильно понравилась ваша программа, решает много проблем)
У меня 4 рутокена используются в 2утм т.к они нужны на 1 пк.
Бывает такое что ключи отваливаются (теряются в системе то 1 то 2 ключа) через devcon я могу виртуально рестартнуть usb порты скриптом, рутокены появляются снова, хотелось бы организовать такой перезапуск раз в час скажем, остановка утм->devcon restar usb-> запуск утм. Можно ли какой то скрипт остановки-запуска?

У меня есть догадки почему отваливаются ключи, но это не точно. Помимо фсраров там же гостовские ключи для входа в сбис, контур-диадок, кабинет налогоплательщика и т.д после того как ключи стали не копируемыми, пришлось поковырять windows и сделать так что бы ключи были видны у каждого человека в rdp сеансе при том что они подключены непосредственно в сервер. То-есть одним рутокеном могут пользоваться 10 человек не зависимо друг от друга. Затык происходит когда 2 человека пытаются одновременно войти на разные платформы где нужны ключи)

**Comment by 2UTM** [comment]
ну вы можете взять код запуска и остановки из исходников, и написать себе этот скрипт
никаких апи в программе нет, не было такой цели
