### ISSUE TITLE
код ошибки 12029

### ISSUE THREAD

**Issue by Stelz481** [2UTM/2UTM#6]
Добрый день в момент установки возникает ошибка -12029
![2024-01-11_16-56-16](https://github.com/2UTM/2UTM/assets/104354712/bf71cdae-6ed0-44f5-b5ed-85abba840cc2)
Подскажите пожалуйста в чем может быть проблема

**Comment by 2UTM** [comment]
Приветствую
12029 - ошибка соединения с сервером, то есть страница утм не ответила в течении 5-ти минут, утм не запустился, или не запускается его веб интерфейс
причину можете посмотреть в логе утм
