### ISSUE TITLE
Не удалось скопировать батники в УТМ ! Код ошибки - 3 . Будет выполнена отмена изменений.

### ISSUE THREAD

**Issue by RomanGit2023** [2UTM/2UTM#7]
![Screenshot_5](https://github.com/2UTM/2UTM/assets/130161875/0a9d2cf8-1c53-48c2-9192-c8d96d7dfd25)

**Comment by 2UTM** [comment]
лог программы покажите
ошибка 3 - это не найден путь

**Comment by RomanGit2023** [comment]
> лог программы покажите ошибка 3 - это не найден путь
15:49:31 23.01.2024 [ERROR]: Не удалось заполнить листбокс
15:49:31 23.01.2024 [INFO]: Обновление устройств выполнено успешно
15:53:16 23.01.2024 [INFO]: Установка УТМ 1
15:53:40 23.01.2024 [INFO]: УТМ 1 успешно установлен
15:53:40 23.01.2024 [INFO]: Объявляем и создаем пайп
15:53:40 23.01.2024 [INFO]: Объявляем и создаем процесс
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Читаем из пайпа
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Чистка
15:53:40 23.01.2024 [INFO]: Служба УТМ удалена
15:53:40 23.01.2024 [INFO]: Батник УТМ исправлен
15:53:40 23.01.2024 [INFO]: Объявляем и создаем пайп
15:53:40 23.01.2024 [INFO]: Объявляем и создаем процесс
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Читаем из пайпа
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:40 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:40 23.01.2024 [INFO]: Ждем завершения процесса
15:53:41 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:41 23.01.2024 [INFO]: Ждем завершения процесса
15:53:41 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:41 23.01.2024 [INFO]: Ждем завершения процесса
15:53:41 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:41 23.01.2024 [INFO]: Ждем завершения процесса
15:53:41 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:41 23.01.2024 [INFO]: Ждем завершения процесса
15:53:41 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:41 23.01.2024 [INFO]: Ждем завершения процесса
15:53:41 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:41 23.01.2024 [INFO]: Ждем завершения процесса
15:53:41 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:41 23.01.2024 [INFO]: Ждем завершения процесса
15:53:41 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:41 23.01.2024 [INFO]: Ждем завершения процесса
15:53:41 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:41 23.01.2024 [INFO]: Ждем завершения процесса
15:53:41 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:41 23.01.2024 [INFO]: Ждем завершения процесса
15:53:41 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:41 23.01.2024 [INFO]: Ждем завершения процесса
15:53:41 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:41 23.01.2024 [INFO]: Ждем завершения процесса
15:53:41 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:41 23.01.2024 [INFO]: Ждем завершения процесса
15:53:41 23.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
15:53:41 23.01.2024 [INFO]: Чистка
15:53:41 23.01.2024 [INFO]: Служба УТМ установлена
15:53:41 23.01.2024 [INFO]: Чтение конфига
15:53:41 23.01.2024 [INFO]: Чтение конфига успешно завершено
15:53:41 23.01.2024 [INFO]: Копируем УТМ 4
15:53:46 23.01.2024 [INFO]: Копирование УТМ 4 успешно завершена
15:53:46 23.01.2024 [INFO]: Копируем батники в УТМ 4
15:54:42 23.01.2024 [ERROR]: Не удалось скопировать батники в УТМ! Код ошибки - 3
Будет выполнена отмена изменений
15:54:42 23.01.2024 [INFO]: Отмена изменений
15:54:42 23.01.2024 [INFO]: Отмена изменений. Удаление всех новых ридеров успешно завершено
15:54:42 23.01.2024 [INFO]: Отмена изменений. Добавление всех старых ридеров успешно завершено
15:54:42 23.01.2024 [INFO]: Отмена изменений. Выполняеться удаление УТМ
15:54:47 23.01.2024 [INFO]: Отмена изменений. Удаление УТМ успешно завершено
15:54:50 23.01.2024 [INFO]: Отмена изменений. Удаление папок и служб УТМ успешно завершено

**Comment by RomanGit2023** [comment]
1 утм устанавливается без проблем, 2 и более с ошибкой уже.

**Comment by 2UTM** [comment]
системный диск у вас С ?
то есть утм ставиться на диск С ?
папки утм создаются?

готовы предоставить доступ к компьютеру? если готовы напишите мне в телеграм @regnorr

**Comment by RomanGit2023** [comment]
> ![Screenshot_5](https://private-user-images.githubusercontent.com/130161875/298954023-0a9d2cf8-1c53-48c2-9192-c8d96d7dfd25.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMzQ3NjIsIm5iZiI6MTcwNjAzNDQ2MiwicGF0aCI6Ii8xMzAxNjE4NzUvMjk4OTU0MDIzLTBhOWQyY2Y4LTFjNTMtNDhjMi05MTkyLWM4ZDk2ZDdkZmQyNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxODI3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzZjNWM0NjUwNGZlMTFjYzgwMjA4Y2E5NjQ5Y2M0MzgyZjY2Mjg4ZmE2NGYwODgwY2RkZjNhNzQwNmNkZDg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eScw_a2sMqgBFznJWWI1s048R6fBuI4-X9UMGTmZXEs)

Решено! 
Удалил Приложение и удалил папку "2UTM_vs"   в C:\Program Files (x86)\ (наверное в каком-то файле была ошибка). Затем установил заново Приложение и всё отлично установилось и запустилось.
