### ISSUE TITLE
Код ошибки 6

### ISSUE THREAD

**Issue by Apocalypse-666** [2UTM/2UTM#8]
Добрый день.
При установке возникает ошибка 6 в момент чистки всех ридеров, После чего происходит откат.
пробовал установить руками, но при запуске он пытается опять же почистить все ридеры и возникает ошибка
выдержка из лога

08:26:17 26.01.2024 [INFO]: Установка УТМ 1
08:26:29 26.01.2024 [INFO]: УТМ 1 успешно установлен
08:26:29 26.01.2024 [INFO]: Объявляем и создаем пайп
08:26:29 26.01.2024 [INFO]: Объявляем и создаем процесс
08:26:29 26.01.2024 [INFO]: Ждем завершения процесса
08:26:29 26.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
08:26:29 26.01.2024 [INFO]: Читаем из пайпа
08:26:29 26.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
08:26:29 26.01.2024 [INFO]: Чистка
08:26:29 26.01.2024 [INFO]: Служба УТМ удалена
08:26:29 26.01.2024 [INFO]: Батник УТМ исправлен
08:26:29 26.01.2024 [INFO]: Объявляем и создаем пайп
08:26:29 26.01.2024 [INFO]: Объявляем и создаем процесс
08:26:29 26.01.2024 [INFO]: Ждем завершения процесса
08:26:29 26.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
08:26:29 26.01.2024 [INFO]: Читаем из пайпа
08:26:29 26.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
08:26:29 26.01.2024 [INFO]: Чистка
08:26:29 26.01.2024 [INFO]: Служба УТМ установлена
08:26:29 26.01.2024 [INFO]: Чтение конфига
08:26:29 26.01.2024 [INFO]: Чтение конфига успешно завершено
08:26:29 26.01.2024 [INFO]: Копируем УТМ 2
08:26:37 26.01.2024 [INFO]: Копирование УТМ 2 успешно завершена
08:26:37 26.01.2024 [INFO]: Копируем батники в УТМ 2
08:26:37 26.01.2024 [INFO]: Копирование батников в УТМ 2 успешно завершена
08:26:37 26.01.2024 [INFO]: Исправляем конфиги в УТМ 2
08:26:37 26.01.2024 [INFO]: Исправление конфигов в УТМ 2 успешно завершена
08:26:37 26.01.2024 [INFO]: Устанавливаем службу УТМ 2
08:26:37 26.01.2024 [INFO]: Объявляем и создаем пайп
08:26:37 26.01.2024 [INFO]: Объявляем и создаем процесс
08:26:37 26.01.2024 [INFO]: Ждем завершения процесса
08:26:37 26.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
08:26:37 26.01.2024 [INFO]: Читаем из пайпа
08:26:37 26.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
08:26:37 26.01.2024 [INFO]: Ждем завершения процесса
08:26:37 26.01.2024 [INFO]: Получаем размер буффера из пайпа не очищая его
08:26:37 26.01.2024 [INFO]: Чистка
08:26:37 26.01.2024 [INFO]: Установка службы УТМ 2 успешно завершена
08:26:37 26.01.2024 [INFO]: Удаление всех ридеров
08:26:41 26.01.2024 [ERROR]: Удаление всех ридеров завершилось ошибкой! Код ошибки - 6
Будет выполнена отмена изменений
08:26:41 26.01.2024 [INFO]: Отмена изменений
08:26:41 26.01.2024 [ERROR]: Отмена изменений. Удаление всех новых ридеров завершилось ошибкой! Код ошибки - 6
08:26:42 26.01.2024 [ERROR]: Отмена изменений завершилась неудачей
08:26:45 26.01.2024 [INFO]: Сбор данных выполнен успешно
08:26:46 26.01.2024 [INFO]: Сбор данных выполнен успешно
08:26:47 26.01.2024 [INFO]: Сбор данных выполнен успешно

**Comment by 2UTM** [comment]
ошибка 6 - неверный хендл
рутокены в драйвере видны? с ними все нормально? как они подключены?
готовы предоставить доступ к ПК ?
если готовы напишите в телеграм @regnorr

**Comment by Apocalypse-666** [comment]
Рутокены видны, в утилите тоже видны,
Возможно связано что это 3 рутокены.
Доступ предоставить смогу

**Comment by 2UTM** [comment]
с рутокенами 3.0 работу не проверял, у меня их нет физически
