### ISSUE TITLE
Удалите самостоятельно уже установленные УТМ

### ISSUE THREAD

**Issue by Ardivald** [2UTM/2UTM#9]
Здравствуйте. Удалил УТМ корректно вроде как, через панель управления. Но выдается сообщение "Удалите самостоятельно уже установленные УТМ!". Где проверка? Что еще посмотреть? 

![image](https://github.com/2UTM/2UTM/assets/147575274/606becfb-976c-4c84-8ab0-44d740cd23de)

**Comment by 2UTM** [comment]
скорее всего осталась папка utm на диске c

**Comment by Ardivald** [comment]
да, на диске С оказались папки-копии UTM. Но с добавочными символами.. типа UTM-копия и т.п.
Спасибо.
